//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7PRAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouseParts
    {
        public int SkladID { get; set; }
        public int PartID { get; set; }
        public int Count { get; set; }
    
        public virtual parts parts { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
